<a href="https://colab.research.google.com/github/AlexeiAltamira/Portfolio/blob/main/Suicidio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Instalação das bibliotecas

In [16]:
# Instalação das bibliotecas
import pandas as pd

In [17]:
dados_suicide = pd.read_csv('https://data.cdc.gov/api/views/9j2v-jamp/rows.csv?accessType=DOWNLOAD')
# Origem dos dados: https://catalog.data.gov/dataset/death-rates-for-suicide-by-sex-race-hispanic-origin-and-age-united-states-020c1
# Usa biblioteca pandas para abrir arquivo data.csv, que contem os dados a serem analisados, direto do site.

In [18]:
dados_suicide.head(3)

,INDICATOR,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE,FLAG
0,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1950,1,All ages,0.0,13.2,NaN
1,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1960,2,All ages,0.0,12.5,NaN
2,Death rates for suicide,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1970,3,All ages,0.0,13.1,NaN

In [19]:
#Identificar tipos dos dados de cada coluna. Observado necessidade de correções (tipo de dados divergentes)
dados_suicide.dtypes

INDICATOR          object
UNIT               object
UNIT_NUM            int64
STUB_NAME          object
STUB_NAME_NUM       int64
STUB_LABEL         object
STUB_LABEL_NUM    float64
YEAR                int64
YEAR_NUM            int64
AGE                object
AGE_NUM           float64
ESTIMATE          float64
FLAG               object
dtype: object

In [20]:
dados_suicide.isna().sum()

INDICATOR            0
UNIT                 0
UNIT_NUM             0
STUB_NAME            0
STUB_NAME_NUM        0
STUB_LABEL           0
STUB_LABEL_NUM       0
YEAR                 0
YEAR_NUM             0
AGE                  0
AGE_NUM              0
ESTIMATE           906
FLAG              5484
dtype: int64

In [21]:
dados_suicide.duplicated().sum()

0

In [22]:
colunas = dados_suicide.columns

In [23]:
for ver in colunas:
  print(f'{ver}\n{dados_suicide[ver].unique()}\n')

INDICATOR
['Death rates for suicide']

UNIT
['Deaths per 100,000 resident population, age-adjusted'
 'Deaths per 100,000 resident population, crude']

UNIT_NUM
[1 2]

STUB_NAME
['Total' 'Sex' 'Sex and race' 'Sex and race and Hispanic origin'
 'Sex and race (Single race)'
 'Sex and race and Hispanic origin (Single race)' 'Age' 'Sex and age'
 'Sex, age and race' 'Sex, age and race and Hispanic origin'
 'Sex, age and race (Single race)'
 'Sex, age and race and Hispanic origin (Single race)']

STUB_NAME_NUM
[ 0  2  4  6  8 10  1  3  5  7  9 11]

STUB_LABEL
['All persons' 'Male' 'Female' 'Male: White'
 'Male: Black or African American'
 'Male: American Indian or Alaska Native'
 'Male: Asian or Pacific Islander' 'Female: White'
 'Female: Black or African American'
 'Female: American Indian or Alaska Native'
 'Female: Asian or Pacific Islander' 'Male: Not Hispanic or Latino: White'
 'Male: Not Hispanic or Latino: Black or African American'
 'Male: Hispanic or Latino: All races'
 'Male: Not Hispanic or Latino: American Indian or Alaska Native'
 'Male: Not Hispanic or Latino: Asian or Pacific Islander'
 'Female: Not Hispanic or Latino: White'
 'Female: Not Hispanic or Latino: Black or African American'
 'Female: Hispanic or Latino: All races'
 'Female: Not Hispanic or Latino: American Indian or Alaska Native'
 'Female: Not Hispanic or Latino: Asian or Pacific Islander'
 'Male: Not Hispanic or Latino: Asian'
 'Male: Not Hispanic or Latino: Native Hawaiian or Other Pacific Islander'
 'Female: Not Hispanic or Latino: Asian'
 'Female: Not Hispanic or Latino: Native Hawaiian or Other Pacific Islander'
 '10-14 years' '15-24 years' '15-19 years' '20-24 years' '25-44 years'
 '25-34 years' '35-44 years' '45-64 years' '45-54 years' '55-64 years'
 '65 years and over' '65-74 years' '75-84 years' '85 years and over'
 'Male: 10-14 years' 'Male: 15-24 years' 'Male: 15-19 years'
 'Male: 20-24 years' 'Male: 25-44 years' 'Male: 25-34 years'
 'Male: 35-44 years' 'Male: 45-64 years' 'Male: 45-54 years'
 'Male: 55-64 years' 'Male: 65 years and over' 'Male: 65-74 years'
 'Male: 75-84 years' 'Male: 85 years and over' 'Female: 10-14 years'
 'Female: 15-24 years' 'Female: 15-19 years' 'Female: 20-24 years'
 'Female: 25-44 years' 'Female: 25-34 years' 'Female: 35-44 years'
 'Female: 45-64 years' 'Female: 45-54 years' 'Female: 55-64 years'
 'Female: 65 years and over' 'Female: 65-74 years' 'Female: 75-84 years'
 'Female: 85 years and over' 'Male: White: 15-24 years'
 'Male: White: 25-44 years' 'Male: White: 45-64 years'
 'Male: White: 65 years and over' 'Male: White: 65-74 years'
 'Male: White: 75-84 years' 'Male: White: 85 years and over'
 'Male: Black or African American: 15-24 years'
 'Male: Black or African American: 25-44 years'
 'Male: Black or African American: 45-64 years'
 'Male: Black or African American: 65 years and over'
 'Male: Black or African American: 65-74 years'
 'Male: Black or African American: 75-84 years'
 'Male: Black or African American: 85 years and over'
 'Male: American Indian or Alaska Native: 15-24 years'
 'Male: American Indian or Alaska Native: 25-44 years'
 'Male: American Indian or Alaska Native: 45-64 years'
 'Male: American Indian or Alaska Native: 65 years and over'
 'Male: Asian or Pacific Islander: 15-24 years'
 'Male: Asian or Pacific Islander: 25-44 years'
 'Male: Asian or Pacific Islander: 45-64 years'
 'Male: Asian or Pacific Islander: 65 years and over'
 'Female: White: 15-24 years' 'Female: White: 25-44 years'
 'Female: White: 45-64 years' 'Female: White: 65 years and over'
 'Female: Black or African American: 15-24 years'
 'Female: Black or African American: 25-44 years'
 'Female: Black or African American: 45-64 years'
 'Female: Black or African American: 65 years and over'
 'Female: American Indian or Alaska Native: 15-24 years'
 'Female: American Indian or Alaska Native: 25-44 years'
 'Female: American Indian or Alaska Native: 45-64 years'
 'Female: American Indian or Alaska Native: 65 years and over'
 'Female: Asian or Pacific Islander: 15-24 years'
 'Female: Asian or Pacific Islander: 25-44 years'
 'Female: Asian or Pacific Islander: 45-64 years'
 'Female: Asian or Pacific Islander: 65 years and over'
 'Male: Not Hispanic or Latino: American Indian or Alaska Native: 15-24 years'
 'Male: Not Hispanic or Latino: White: 15-24 years'
 'Male: Not Hispanic or Latino: American Indian or Alaska Native: 25-44 years'
 'Male: Not Hispanic or Latino: American Indian or Alaska Native: 45-64 years'
 'Male: Not Hispanic or Latino: American Indian or Alaska Native: 65 years and over'
 'Male: Not Hispanic or Latino: Asian or Pacific Islander: 15-24 years'
 'Male: Not Hispanic or Latino: Asian or Pacific Islander: 25-44 years'
 'Male: Not Hispanic or Latino: Asian or Pacific Islander: 45-64 years'
 'Male: Not Hispanic or Latino: Asian or Pacific Islander: 65 years and over'
 'Female: Not Hispanic or Latino: American Indian or Alaska Native: 15-24 years'
 'Female: Not Hispanic or Latino: American Indian or Alaska Native: 25-44 years'
 'Female: Not Hispanic or Latino: American Indian or Alaska Native: 45-64 years'
 'Female: Not Hispanic or Latino: American Indian or Alaska Native: 65 years and over'
 'Female: Not Hispanic or Latino: Asian or Pacific Islander: 15-24 years'
 'Female: Not Hispanic or Latino: Asian or Pacific Islander: 25-44 years'
 'Female: Not Hispanic or Latino: Asian or Pacific Islander: 45-64 years'
 'Female: Not Hispanic or Latino: Asian or Pacific Islander: 65 years and over'
 'Male: Not Hispanic or Latino: White: 25-44 years'
 'Male: Not Hispanic or Latino: White: 45-64 years'
 'Male: Not Hispanic or Latino: White: 65 years and over'
 'Male: Not Hispanic or Latino: Black or African American: 15-24 years'
 'Male: Not Hispanic or Latino: Black or African American: 25-44 years'
 'Male: Not Hispanic or Latino: Black or African American: 45-64 years'
 'Male: Not Hispanic or Latino: Black or African American: 65 years and over'
 'Male: Hispanic or Latino: All races: 15-24 years'
 'Male: Hispanic or Latino: All races: 25-44 years'
 'Male: Hispanic or Latino: All races: 45-64 years'
 'Male: Hispanic or Latino: All races: 65 years and over'
 'Female: Not Hispanic or Latino: White: 15-24 years'
 'Female: Not Hispanic or Latino: White: 25-44 years'
 'Female: Not Hispanic or Latino: White: 45-64 years'
 'Female: Not Hispanic or Latino: White: 65 years and over'
 'Female: Not Hispanic or Latino: Black or African American: 15-24 years'
 'Female: Not Hispanic or Latino: Black or African American: 25-44 years'
 'Female: Not Hispanic or Latino: Black or African American: 45-64 years'
 'Female: Not Hispanic or Latino: Black or African American: 65 years and over'
 'Female: Hispanic or Latino: All races: 15-24 years'
 'Female: Hispanic or Latino: All races: 25-44 years'
 'Female: Hispanic or Latino: All races: 45-64 years'
 'Female: Hispanic or Latino: All races: 65 years and over'
 'Male: Not Hispanic or Latino: Asian: 15-24 years'
 'Male: Not Hispanic or Latino: Asian: 25-44 years'
 'Male: Not Hispanic or Latino: Asian: 45-64 years'
 'Male: Not Hispanic or Latino: Asian: 65 years and over'
 'Male: Not Hispanic or Latino: Native Hawaiian or Other Pacific Islander: 15-24 years'
 'Male: Not Hispanic or Latino: Native Hawaiian or Other Pacific Islander: 25-44 years'
 'Male: Not Hispanic or Latino: Native Hawaiian or Other Pacific Islander: 45-64 years'
 'Male: Not Hispanic or Latino: Native Hawaiian or Other Pacific Islander: 65 years and over'
 'Female: Not Hispanic or Latino: Asian: 15-24 years'
 'Female: Not Hispanic or Latino: Asian: 25-44 years'
 'Female: Not Hispanic or Latino: Asian: 45-64 years'
 'Female: Not Hispanic or Latino: Asian: 65 years and over'
 'Female: Not Hispanic or Latino: Native Hawaiian or Other Pacific Islander: 15-24 years'
 'Female: Not Hispanic or Latino: Native Hawaiian or Other Pacific Islander: 25-44 years'
 'Female: Not Hispanic or Latino: Native Hawaiian or Other Pacific Islander: 45-64 years'
 'Female: Not Hispanic or Latino: Native Hawaiian or Other Pacific Islander: 65 years and over']

STUB_LABEL_NUM
[0.     2.1    2.2    4.11   4.12   4.13   4.14   4.21   4.22   4.23
 4.24   6.11   6.12   6.13   6.14   6.15   6.21   6.22   6.23   6.24
 6.25   6.16   6.17   6.26   6.27   1.1    1.2    1.21   1.22   1.3
 1.31   1.32   1.4    1.41   1.42   1.5    1.51   1.52   1.53   3.11
 3.12   3.121  3.122  3.13   3.131  3.132  3.14   3.141  3.142  3.15
 3.151  3.152  3.153  3.21   3.22   3.221  3.222  3.23   3.231  3.232
 3.24   3.241  3.242  3.25   3.251  3.252  3.253  5.112  5.113  5.114
 5.115  5.1151 5.1152 5.1153 5.122  5.123  5.124  5.125  5.1251 5.1252
 5.1253 5.132  5.133  5.134  5.135  5.142  5.143  5.144  5.145  5.212
 5.213  5.214  5.215  5.222  5.223  5.224  5.225  5.232  5.233  5.234
 5.235  5.242  5.243  5.244  5.245  6.141  7.112  6.142  6.143  6.144
 6.151  6.152  6.153  6.154  6.241  6.242  6.243  6.244  6.251  6.252
 6.253  6.254  7.113  7.114  7.115  7.122  7.123  7.124  7.125  7.132
 7.133  7.134  7.135  7.212  7.213  7.214  7.215  7.222  7.223  7.224
 7.225  7.232  7.233  7.234  7.235  6.161  6.162  6.163  6.164  6.171
 6.172  6.173  6.174  6.261  6.262  6.263  6.264  6.271  6.272  6.273
 6.274 ]

YEAR
[1950 1960 1970 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990
 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018]

YEAR_NUM
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42]

AGE
['All ages' '10-14 years' '15-24 years' '15-19 years' '20-24 years'
 '25-44 years' '25-34 years' '35-44 years' '45-64 years' '45-54 years'
 '55-64 years' '65 years and over' '65-74 years' '75-84 years'
 '85 years and over']

AGE_NUM
[0.  1.  2.  2.1 2.2 3.  3.1 3.2 4.  4.1 4.2 5.  5.1 5.2 6. ]

ESTIMATE
[13.2 12.5 13.1 12.2 12.3 12.4 12.6 13.  12.8 12.  12.1 11.9 11.8 11.5
 11.2 11.1 10.5 10.4 10.7 10.9 10.8 11.  11.3 11.6 13.3 13.5 14.  14.2
 21.2 20.  19.8 19.9 20.4 20.9 21.1 21.9 21.7 21.  21.5 20.5 20.7 20.3
 19.1 18.9 17.8 17.7 18.2 18.5 18.1 19.  19.2 21.4 22.4 22.8  5.6  7.4
  5.7  6.   5.8  5.5  5.2  5.3  5.1  4.9  4.8  4.7  4.6  4.4  4.3  4.
  4.1  4.2  4.5  5.   5.4  6.1  6.2 22.3 20.8 21.6 22.1 23.2 23.  22.5
 21.8 19.6 20.1 19.7 22.  22.6 23.3 23.6 23.9 25.1 25.5  7.5  8.4 10.
 11.4 11.7 12.9 10.3  9.8  9.9  9.2  9.6  9.4  8.7  8.9  9.1  9.3  9.5
 10.2  nan 19.3 18.6 18.  17.9 18.8 17.6 16.9 17.5 17.4 16.5 16.  17.2
 16.1 17.3 15.9 15.4 14.6 15.5 16.4  9.7  8.8  9.   8.6  8.3  8.   8.5
  7.3  7.8  7.9 10.1  5.9  6.4  6.3  6.6  6.9  7.   1.8  2.   2.9  2.4
  2.5  2.3  2.2  2.1  1.9  1.7  1.6  1.4  2.7  2.8  3.3  3.   3.5  3.4
  3.6  3.2  3.7  3.9  3.8  6.5  3.1 22.9 22.2 23.5 21.3 20.2 23.1 23.4
 24.2 24.8 25.2 25.3 25.9 26.6 28.2 28.4 10.6 15.1 13.7 13.9 12.7 19.5
 24.  24.1 24.9 25.6 29.3 27.4 30.3 33.1 33.8 34.2  6.7  7.1  2.6  7.2
  8.1 28.6 33.6 13.4 14.5 14.8  0.3  0.5  0.6  0.8  0.9  1.1  1.3  1.5
  1.2  1.  13.6 15.7 15.2 15.  14.9 15.6 15.8 17.  16.2 15.3 14.7 14.3
 13.8 14.1 16.3 14.4 16.7 16.6 17.1 20.6 16.8 26.8 23.7 18.7 30.  24.5
 18.4 29.6 18.3 31.1 27.9 25.  28.8 26.  19.4 23.8  8.2 22.7 25.7 25.4
 26.5 28.  27.  27.2 24.6 24.3 24.4 26.2 27.5 27.7 24.7 25.8 27.6 26.3
 28.1 37.1 34.4 29.2 28.9 29.5 29.  29.7 29.1 30.1 31.  32.  31.6 30.4
 30.2 29.4 43.6 38.1 32.7 27.1 26.1 27.3 28.7 28.3 29.8 31.7 52.8 44.
 38.4 35.  33.5 36.5 39.3 40.9 43.4 44.2 42.7 41.7 41.6 40.1 38.3 36.2
 35.1 32.2 31.4 31.8 30.9 32.5 50.5 39.6 36.  31.2 31.5 33.9 36.3 35.8
 34.  30.7 29.9 28.5 27.8 58.3 52.5 42.8 42.3 41.4 45.3 49.2 48.5 53.1
 54.9 57.2 57.3 51.5 56.1 53.  50.1 49.  47.1 44.9 43.5 41.1 42.5 38.8
 38.6 37.7 38.  34.9 34.6 35.5 32.9 32.3 34.7 35.2 37.4 57.4 42.4 50.6
 54.2 52.2 56.2 62.1 67.5 61.5 68.2 65.9 69.5 62.4 67.9 66.2 62.7 60.5
 61.  59.8 57.1 57.5 52.7 54.5 51.6 49.9 48.  46.6 43.  47.3 44.1 46.9
 48.2 47.2  0.4  0.7  7.7  7.6  6.8 31.9 30.8 33.  32.8 33.2 34.5 55.8
 46.7 37.2 35.7 38.9 40.5 41.9 43.7 46.1 45.7 44.3 42.6 40.7 38.5 37.6
 35.9 33.3 32.1 34.1 34.3 53.2 42.  38.7 38.2 31.3 26.4 26.7 61.9 55.7
 45.5 43.9 51.9 57.  58.8 60.9 61.4 55.3 60.2 52.1 47.7 46.3 45.1 41.2
 40.  40.4 37.3 36.8 35.4 36.1 35.3 37.  39.7 39.8 61.3 45.8 54.  57.9
 56.3 66.5 72.1 72.9 70.3 74.8 67.1 73.2 71.  65.5 65.2 64.5 61.6 56.6
 57.8 55.2 50.8 47.  50.7 52.6 54.4 51.8 41.8 49.1 39.1 42.1 30.6 32.6
 26.9 34.8 40.2 41.3 44.4 44.6 47.5 51.7 53.7 58.4 36.4 41.5 36.9 40.8
 58.1 59.7 30.5 35.6 46.4 45.4 41.  39.5 39.  33.4 37.5 60.7]

FLAG
[nan '...' '*']

In [24]:
dados_suicide = dados_suicide.drop(['INDICATOR'], axis=1)
dados_suicide = dados_suicide.drop(['FLAG'], axis=1)
#Elimina as colunad 'INDICATOR' e 'FLAG' por não apresentarem dados relavantes para análise

In [25]:
dados_suicide['UNIT'].unique()

array(['Deaths per 100,000 resident population, age-adjusted',
       'Deaths per 100,000 resident population, crude'], dtype=object)

In [26]:
dados_age_adjusted = dados_suicide[(dados_suicide['UNIT'] == 'Deaths per 100,000 resident population, age-adjusted')]

In [27]:
dados_age_adjusted.head(3)

,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE
0,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1950,1,All ages,0.0,13.2
1,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1960,2,All ages,0.0,12.5
2,"Deaths per 100,000 resident population, age-ad...",1,Total,0,All persons,0.0,1970,3,All ages,0.0,13.1

In [28]:
dados_age_adjusted['UNIT'].unique()

array(['Deaths per 100,000 resident population, age-adjusted'],
      dtype=object)

In [29]:
dados_age_adjusted['STUB_NAME_NUM'].count

<bound method Series.count of 0       0
1       0
2       0
3       0
4       0
       ..
809    10
810    10
811    10
812    10
813    10
Name: STUB_NAME_NUM, Length: 812, dtype: int64>

In [30]:
dados_suicide[(dados_suicide['UNIT'] == 'Deaths per 100,000 resident population, crude')].head(3)

,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE
698,"Deaths per 100,000 resident population, crude",2,Total,0,All persons,0.0,1980,4,All ages,0.0,11.9
728,"Deaths per 100,000 resident population, crude",2,Total,0,All persons,0.0,1981,5,All ages,0.0,12.0
814,"Deaths per 100,000 resident population, crude",2,Total,0,All persons,0.0,1950,1,All ages,0.0,11.4